import { Router } from 'express';
import { healthDataRouter } from './health-data.js';
import { healthDataTimeseriesRouter } from './health-data-timeseries.js';
import { settingsRouter } from './settings.js';
import { customInstructionsRouter } from './custom-instructions.js';
import { customDataTypesRouter } from './custom-data-types.js';
import { dataTypesRouter } from './data-types.js';
import { reportsRouter } from './reports.js';
import { pluginsRouter } from './plugins.js';
import { schedulerRouter } from './scheduler.js';
import { chatRouter } from './chat.js';
import { webhooksRouter } from './webhooks.js';
import { chatConversationsRouter } from './chat-conversations.js';
import { healthImagesRouter } from './health-images.js';

export const router = Router();

router.use('/health-data', healthDataRouter);
router.use('/health-data/timeseries', healthDataTimeseriesRouter);
router.use('/settings', settingsRouter);
router.use('/custom-instructions', customInstructionsRouter);
router.use('/custom-data-types', customDataTypesRouter);
router.use('/data-types', dataTypesRouter);
router.use('/reports', reportsRouter);
router.use('/plugins', pluginsRouter);
router.use('/scheduler', schedulerRouter);
router.use('/chat', chatRouter);
router.use('/webhooks', webhooksRouter);
router.use('/chat/conversations', chatConversationsRouter);
router.use('/health-images', healthImagesRouter);
